language: node_js
node_js:
- '10'
branchs:
  only:
  - master
install:
- yarn install
script:
- yarn build
addons:
  ssh_known_hosts:
  - 39.96.191.154
before_install:
- openssl aes-256-cbc -K $encrypted_e6c41ade86ae_key -iv $encrypted_e6c41ade86ae_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@39.96.191.154 -o StrictHostKeyChecking=no 'cd ~/markdown-nice && git
  pull && yarn install && yarn build'
